# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: biglexj.LunaFetch
PackageVersion: 1.0.3
InstallerType: wix
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: ' {E315D83E-7141-3233-8DB6-91907B743A13}'
ReleaseDate: 2026-07-18
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/biglexj/Luna---Fetch/releases/download/v1.0.3/LunaFetch-Windows-1.0.3.msi
    InstallerSha256: E51F0C801F5CDEC894D077CFA6BDCB3AD9180C9E8E0B5CE42192AEFACDF0D3F9
ManifestType: installer
ManifestVersion: 1.10.0